App_MVC/Controllers/ChucVuController.cs
using App_Data_ClassLib.Models;
using App_Data_ClassLib.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace App_MVC.Controllers
{
    public class ChucVuController : Controller
    {
        // GET: ChucVuController
        SD18302_NET104Context _context;
        DbSet<ChucVu> _chuVu;
        AllRepository<ChucVu> _repository;
        public ChucVuController()
        {
            _context = new SD18302_NET104Context();
            _chuVu = _context.ChucVus;
            _repository = new AllRepository<ChucVu>(_chuVu, _context);
        }
        public ActionResult Index()
        {
            var data = _repository.GetAll();
            return View(data);
        }

        // GET: ChucVuController/Details/5
        public ActionResult Details(Guid id)
        {
            var data = _repository.GetByID(id);
            return View(data);
        }

        // GET: ChucVuController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ChucVuController/Create
        [HttpPost]
        public ActionResult Create(ChucVu chucVu)
        {
            Guid id = new Guid();
            try
            {
                chucVu.IdChucVu = id;
                _repository.CreateObj(chucVu);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ChucVuController/Edit/5
        public ActionResult Edit(Guid id)
        {
            var data = _repository.GetByID(id);
            return View(data);
        }

        // POST: ChucVuController/Edit/5
        [HttpPost]
        public ActionResult Edit(ChucVu chucVu)
        {
            try
            {
                _repository.UpdateObj(chucVu);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ChucVuController/Delete/5
        public ActionResult Delete(Guid id)
        {
            _repository.DeleteObj(id);
            return RedirectToAction("Index");
        }

        // POST: ChucVuController/Delete/5
        
    }
}

App_MVC/Controllers/DanhMucController.cs
using App_Data_ClassLib.Models;
using App_Data_ClassLib.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace App_MVC.Controllers
{
    public class DanhMucController : Controller
    {
        SD18302_NET104Context _context;
        DbSet<DanhMucSP> _danhMucSP;
        AllRepository<DanhMucSP> _repository;
        public DanhMucController()
        {
            _context = new SD18302_NET104Context();
            _danhMucSP = _context.DanhMucSPs;
            _repository = new AllRepository<DanhMucSP>(_danhMucSP, _context);
        }
        public IActionResult Index()
        {
            var danhMuc = _repository.GetAll();
            return View(danhMuc);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(DanhMucSP danhMuc)
        {
            danhMuc.ID = Guid.NewGuid();
            _repository.CreateObj(danhMuc);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(Guid id)
        {
            var updateData = _repository.GetByID(id);
            return View(updateData);
        }
        [HttpPost]
        public IActionResult Edit(DanhMucSP danhMucSP)
        {
            _repository.UpdateObj(danhMucSP);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(Guid id)
        {
            _repository.DeleteObj(id);
            return RedirectToAction("Index");
        }
        public IActionResult Details(Guid id)
        {
            var getdanhMuc = _repository.GetByID(id);
            return View(getdanhMuc);
        }
    }
}

App_MVC/Controllers/SanPhamController.cs
using App_Data_ClassLib.Models;
using App_Data_ClassLib.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace App_MVC.Controllers
{
    public class SanPhamController : Controller
    {
        SD18302_NET104Context _context;
        DbSet<SanPham> _sanPham;
        AllRepository<SanPham> _repository;
        public SanPhamController()
        {
            //Khởi tạo dbcontext
            _context = new SD18302_NET104Context();
            //Khỏi tạo repository với 2 tham số dbset và dbcontext
            _sanPham = _context.SanPhams;
            _repository = new AllRepository<SanPham>(_sanPham, _context);
        }
        //Lấy ra tất cả danh sách Sản phẩm
        public IActionResult Index()
        {
            var sanPham = _repository.GetAll();
            return View(sanPham);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(SanPham sanPham,IFormFile imgFile)
        {
            sanPham.IdSP = Guid.NewGuid();
            //Xây dựng 1 đường dẫn lưu hình ảnh
            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", imgFile.FileName);
            //Kết quả thu được có dạng như sau: wwwroot/img/config.png
            //Thực hiện sao chép file được chọn vào thư mục
            var stream = new FileStream(path, FileMode.Create);
            //Thực hiện sao chép ảnh vào thư mục root
            imgFile.CopyTo(stream);
            sanPham.Anh = imgFile.FileName;
            _repository.CreateObj(sanPham);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(Guid id)
        {
            var updateData = _repository.GetByID(id);
            return View(updateData);
        }

        [HttpPost]
        public IActionResult Edit(SanPham sanPham, IFormFile imgFile)
        {
            if (imgFile != null && imgFile.Length > 0)
            {
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img");
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + imgFile.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    imgFile.CopyTo(fileStream);
                }

                sanPham.Anh = uniqueFileName; // Lưu tên tệp vào cơ sở dữ liệu, không phải là imgFile.FileName
            }

            _repository.UpdateObj(sanPham);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(Guid id)
        {
            _repository.DeleteObj(id);
            return RedirectToAction("Index");
        }
        //Thông tin
        public IActionResult Details(Guid id)
        {
            var getSanPham = _repository.GetByID(id);
            return View(getSanPham);
        }


    }
}

App_MVC/Controllers/UserController.cs
using App_Data_ClassLib.Models;
using App_Data_ClassLib.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;


namespace App_MVC.Controllers
{
    public class UserController : Controller
    {
        SD18302_NET104Context _context;
        DbSet<User> _users;
        AllRepository<User> _repository;
        
        public UserController()
        {
            //Khởi tạo DBcontext
            _context = new SD18302_NET104Context();
            //Khởi tạo repository với 2 tham số là DbSet và DbContext
            _users = _context.Users;
            _repository = new AllRepository<User>(_users, _context);
        }
        //Lấy ra tất cả danh sách user
        public IActionResult Index(string name) // tham số name để tìm kiếm
        {
            var sessionData = HttpContext.Session.GetString("user");
            if (sessionData == null)
            {
                ViewData["message"] = "Bạn chưa đăng nhập hoặc hết phiên đăng nhập";
            }
            else
            {
                ViewData["message"] = $"Chào mừng {sessionData} đến với bình nguyên vô tận"; 
            }
            var userData = _repository.GetAll();
            if (string.IsNullOrEmpty(name))
            {
                return View(userData);
            }
            else
            {
                var searchData = _repository.GetAll().Where(x => x.Name.Contains(name)).ToList(); // Tìm theo tên           
                ViewData["count"] = searchData.Count;
                ViewBag.Count = searchData.Count;
                if (searchData.Count == 0) // Nếu ko tìm thấy 
                {
                    return View(userData);
                }
                else return View(searchData); // có tìm thấy
            }

        }
        //Thêm data 
        public IActionResult Create()//Action để mở form điền thông tin user
        {
            return View();
        }
        //Action để thực hiện thêm vào db
        [HttpPost]
        public IActionResult Create(User user)
        {
            user.Id = Guid.NewGuid();
            _repository.CreateObj(user);
            return RedirectToAction("Index","Home");
        }
        //Sửa
        public IActionResult Edit(Guid id)//Form load ra đối tượng cần sửa
        {
            //Lấy ra đối tượng cần sửa
            var updateUser = _repository.GetByID(id);
            return View(updateUser);
        }
        public IActionResult EditUser(User user)// Action này thực hiện thay đổi khi cần thì trỏ tới nó
        {
            _repository.UpdateObj(user);
            return RedirectToAction("Index");
        }
        //Xóa
        public IActionResult Delete(Guid id)
        {
            //Lấy ra đối tượng cần xóa 
            var deleteUser = _repository.GetByID(id);
            var jsondata = JsonConvert.SerializeObject(deleteUser);//Ép kiểu sang Json
            HttpContext.Session.SetString("deleted", jsondata);//Cho dữ liệu vào Json 
            _repository.DeleteObj(id);
            return RedirectToAction("Index");
        }
        public IActionResult RollBack()
        {
            if (HttpContext.Session.Keys.Contains("deleted"))
            {
                var jsondata = HttpContext.Session.GetString("deleted");
                //Tạo mới đối tượng có dữ liệu với đối tượng y hệt dữ liệu cũ
                var deleted = JsonConvert.DeserializeObject<User>(jsondata);
                _repository.CreateObj(deleted);//Thêm mới vào db
                return RedirectToAction("Index");//Về trang Index  
            }
            else
            {
                return Content("Đã quá muộn rồi");
            }
        }
        //Thông tin
        public IActionResult Details(Guid id)
        {
            var getUser = _repository.GetByID(id);
            return View(getUser);
        }
        public IActionResult Login()// Action này return về view để mở view cho phép nhập thông tin đăng nhập
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(string username , string password)//Action này để đăng nhập
        {
            var user = _repository.GetAll().FirstOrDefault(p => p.Username == username && p.Password == password);
            if (user != null)
            {
                //return Content("Đăng nhập thành công");
                //Dùng temData để lưu trữ dữ liệu tạm thời
                TempData["Login"] = username;
                //Lưu trữ thông tin đăng nhập vào session
                HttpContext.Session.SetString("user",user.Id.ToString());
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return Content("Đăng nhập thất bại");
            }
        }
       public IActionResult Logout()
        {
            HttpContext.Session.Remove("user");
            return RedirectToAction("Index","Home");
        }
    }
}

App_MVC/Views/Shared/_Layout.cshtml
@using App_Data_ClassLib.Models;
@{
     var dbContext = new SD18302_NET104Context();
}
@{
    var logout = Context.Request.HttpContext.Session.GetString("user");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/App_MVC.styles.css" asp-append-version="true" />
    <!-- Font Awesome for icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm border-bottom border-body bg-black shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/logo.jpg" alt="BookStore Logo" height="55"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Các mục bên trái -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-white active" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white active" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white active" asp-area="" asp-controller="SanPham" asp-action="Index">Sản Phẩm</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white active" asp-area="" asp-controller="DanhMuc" asp-action="Index">Danh Mục Sản Phẩm</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-white active" asp-area="" asp-controller="ChucVu" asp-action="Index">Danh Mục chức vụ</a>
                        </li>
                    </ul>
                    <!-- Thanh tìm kiếm ở giữa -->
                    <form class="d-flex form-inline my-2 my-lg-0 mx-auto" role="search" action="/Home/Index" method="get">
                        <input class="form-control mr-sm-2" style="width: 400px;" type="text" name="name" placeholder="Tìm kiếm" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0"  style="margin-left:10px;" type="submit">Tìm kiếm</button>
                    </form>
                    <!-- Các mục bên phải -->
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-white active" asp-area="" asp-controller="GioHang" asp-action="Index">
                                <i class="fas fa-shopping-cart nav-link text-white"></i> Giỏ hàng
                            </a>
                        </li>
                        @if(string.IsNullOrEmpty(logout)){
                            <li class="nav-item">
                            <a class="nav-link text-white active" asp-area="" asp-controller="User" asp-action="Login">
                                <i class="fas fa-user nav-link text-white"></i> Tài khoản
                            </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                            <a class="nav-link text-white active" asp-area="" asp-controller="User" asp-action="Logout">
                                <i class="fas fa-user nav-link text-white"></i> Đăng xuất
                            </a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- footer -->
        <footer class="bg-dark text-light text-center py-5">
            <div class="container">
              <div class="row">
                <div class="col-lg-4">
                  <img src="~/img/logo.jpg" alt="Logo" class="footer-logo">
                  <p>Trường Cao Đẳng FPT<br>Hà Nội, Việt Nam</p>
                </div>
                <div class="col-lg-4">
                  <h5>Liên hệ</h5>
                  <p>Email: contact@example.com<br>Điện thoại: (123) 456-7890</p>
                </div>
                <div class="col-lg-4">
                  <h5>Theo dõi chúng tôi</h5>
                  <p>Đăng ký để nhận thông tin cập nhật về sản phẩm và dịch vụ của chúng tôi.</p>
                  <form>
                    <div class="input-group mb-3">
                      <input type="email" class="form-control" placeholder="Địa chỉ Email" aria-label="Địa chỉ Email" aria-describedby="basic-addon2">
                      <div class="input-group-append">
                        <button class="btn btn-warning" type="button">Đăng ký</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <div class="container mt-4">
              <hr class="my-4">
              <p>&copy; 2024 Đồng Minh Toản PH33341.</p>
            </div>
          </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
 <style>
        /* CSS tùy chỉnh để làm đẹp footer */
        footer {
          background-color: #343a40; /* Màu nền */
          color: #fff; /* Màu chữ */
          padding: 60px 0; /* Khoảng cách padding */
        }
    
        .footer-logo {
          max-width: 100px; /* Độ rộng tối đa cho logo */
        }
    
        /* Tùy chỉnh một số kiểu chữ */
        h5 {
          color: #ffc107; /* Màu chữ cho tiêu đề */
        }
    
        p {
          font-size: 16px; /* Kích thước chữ cho đoạn văn bản */
        }
      </style>